name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: npm install
      - run: npm run build

  test-unit:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: npm run test

  test-e2e:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: cypress-io/github-action@v2
        with:
          build: npm run build
          browser: chrome
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
